// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteCampsitesByIdData, DeleteCampsitesByIdErrors, DeleteCampsitesByIdResponses, DeleteReviewsByIdData, DeleteReviewsByIdErrors, DeleteReviewsByIdResponses, DeleteUsersMeData, DeleteUsersMeErrors, DeleteUsersMeResponses, GetCampsitesByIdData, GetCampsitesByIdErrors, GetCampsitesByIdResponses, GetDatabaseHealthData, GetDatabaseHealthErrors, GetDatabaseHealthResponses, GetReviewsByIdData, GetReviewsByIdErrors, GetReviewsByIdResponses, GetUsersByIdData, GetUsersByIdErrors, GetUsersByIdResponses, GetUsersMeData, GetUsersMeErrors, GetUsersMeResponses, PatchCampsitesByIdData, PatchCampsitesByIdErrors, PatchCampsitesByIdResponses, PatchReviewsByIdData, PatchReviewsByIdErrors, PatchReviewsByIdResponses, PatchUsersMeData, PatchUsersMeErrors, PatchUsersMeResponses, PostCampsitesByIdReviewsData, PostCampsitesByIdReviewsErrors, PostCampsitesByIdReviewsResponses, PostCampsitesData, PostCampsitesErrors, PostCampsitesResponses, PostCampsitesSearchData, PostCampsitesSearchErrors, PostCampsitesSearchResponses, PostDatabaseMigrationsData, PostDatabaseMigrationsErrors, PostDatabaseMigrationsResponses, PostReviewsSearchData, PostReviewsSearchErrors, PostReviewsSearchResponses, PostUsersData, PostUsersErrors, PostUsersResponses, PostUsersSearchData, PostUsersSearchErrors, PostUsersSearchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Post campsites
 */
export const postCampsites = <ThrowOnError extends boolean = false>(options: Options<PostCampsitesData, ThrowOnError>) => (options.client ?? client).post<PostCampsitesResponses, PostCampsitesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post campsites search
 */
export const postCampsitesSearch = <ThrowOnError extends boolean = false>(options: Options<PostCampsitesSearchData, ThrowOnError>) => (options.client ?? client).post<PostCampsitesSearchResponses, PostCampsitesSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete campsites by ID
 */
export const deleteCampsitesById = <ThrowOnError extends boolean = false>(options: Options<DeleteCampsitesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteCampsitesByIdResponses, DeleteCampsitesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites/{id}',
    ...options
});

/**
 * Get campsites by ID
 */
export const getCampsitesById = <ThrowOnError extends boolean = false>(options: Options<GetCampsitesByIdData, ThrowOnError>) => (options.client ?? client).get<GetCampsitesByIdResponses, GetCampsitesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites/{id}',
    ...options
});

/**
 * Patch campsites by ID
 */
export const patchCampsitesById = <ThrowOnError extends boolean = false>(options: Options<PatchCampsitesByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchCampsitesByIdResponses, PatchCampsitesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post campsites by ID reviews
 */
export const postCampsitesByIdReviews = <ThrowOnError extends boolean = false>(options: Options<PostCampsitesByIdReviewsData, ThrowOnError>) => (options.client ?? client).post<PostCampsitesByIdReviewsResponses, PostCampsitesByIdReviewsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/campsites/{id}/reviews',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get database health
 */
export const getDatabaseHealth = <ThrowOnError extends boolean = false>(options?: Options<GetDatabaseHealthData, ThrowOnError>) => (options?.client ?? client).get<GetDatabaseHealthResponses, GetDatabaseHealthErrors, ThrowOnError>({ url: '/database/health', ...options });

/**
 * Post database migrations
 */
export const postDatabaseMigrations = <ThrowOnError extends boolean = false>(options?: Options<PostDatabaseMigrationsData, ThrowOnError>) => (options?.client ?? client).post<PostDatabaseMigrationsResponses, PostDatabaseMigrationsErrors, ThrowOnError>({ url: '/database/migrations', ...options });

/**
 * Post reviews search
 */
export const postReviewsSearch = <ThrowOnError extends boolean = false>(options: Options<PostReviewsSearchData, ThrowOnError>) => (options.client ?? client).post<PostReviewsSearchResponses, PostReviewsSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reviews/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete reviews by ID
 */
export const deleteReviewsById = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteReviewsByIdResponses, DeleteReviewsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reviews/{id}',
    ...options
});

/**
 * Get reviews by ID
 */
export const getReviewsById = <ThrowOnError extends boolean = false>(options: Options<GetReviewsByIdData, ThrowOnError>) => (options.client ?? client).get<GetReviewsByIdResponses, GetReviewsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reviews/{id}',
    ...options
});

/**
 * Patch reviews by ID
 */
export const patchReviewsById = <ThrowOnError extends boolean = false>(options: Options<PatchReviewsByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchReviewsByIdResponses, PatchReviewsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reviews/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post users
 */
export const postUsers = <ThrowOnError extends boolean = false>(options: Options<PostUsersData, ThrowOnError>) => (options.client ?? client).post<PostUsersResponses, PostUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete users me
 */
export const deleteUsersMe = <ThrowOnError extends boolean = false>(options?: Options<DeleteUsersMeData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUsersMeResponses, DeleteUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Get users me
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetUsersMeResponses, GetUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Patch users me
 */
export const patchUsersMe = <ThrowOnError extends boolean = false>(options: Options<PatchUsersMeData, ThrowOnError>) => (options.client ?? client).patch<PatchUsersMeResponses, PatchUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post users search
 */
export const postUsersSearch = <ThrowOnError extends boolean = false>(options: Options<PostUsersSearchData, ThrowOnError>) => (options.client ?? client).post<PostUsersSearchResponses, PostUsersSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get users by ID
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, GetUsersByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options
});
