// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUsersMeData, DeleteUsersMeErrors, DeleteUsersMeResponses, GetDatabaseHealthData, GetDatabaseHealthErrors, GetDatabaseHealthResponses, GetUsersByIdData, GetUsersByIdErrors, GetUsersByIdResponses, GetUsersMeData, GetUsersMeErrors, GetUsersMeResponses, PostDatabaseMigrationsData, PostDatabaseMigrationsErrors, PostDatabaseMigrationsResponses, PostUsersData, PostUsersErrors, PostUsersResponses, PostUsersSearchData, PostUsersSearchErrors, PostUsersSearchResponses, PutUsersMeData, PutUsersMeErrors, PutUsersMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get database health
 */
export const getDatabaseHealth = <ThrowOnError extends boolean = false>(options?: Options<GetDatabaseHealthData, ThrowOnError>) => (options?.client ?? client).get<GetDatabaseHealthResponses, GetDatabaseHealthErrors, ThrowOnError>({ url: '/database/health', ...options });

/**
 * Post database migrations
 */
export const postDatabaseMigrations = <ThrowOnError extends boolean = false>(options?: Options<PostDatabaseMigrationsData, ThrowOnError>) => (options?.client ?? client).post<PostDatabaseMigrationsResponses, PostDatabaseMigrationsErrors, ThrowOnError>({ url: '/database/migrations', ...options });

/**
 * Post users
 */
export const postUsers = <ThrowOnError extends boolean = false>(options: Options<PostUsersData, ThrowOnError>) => (options.client ?? client).post<PostUsersResponses, PostUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete users me
 */
export const deleteUsersMe = <ThrowOnError extends boolean = false>(options?: Options<DeleteUsersMeData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUsersMeResponses, DeleteUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Get users me
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetUsersMeResponses, GetUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Put users me
 */
export const putUsersMe = <ThrowOnError extends boolean = false>(options: Options<PutUsersMeData, ThrowOnError>) => (options.client ?? client).put<PutUsersMeResponses, PutUsersMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post users search
 */
export const postUsersSearch = <ThrowOnError extends boolean = false>(options: Options<PostUsersSearchData, ThrowOnError>) => (options.client ?? client).post<PostUsersSearchResponses, PostUsersSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get users by ID
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, GetUsersByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options
});
