// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CampsiteProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    boondockScore: number;
    createdAt: string;
    description: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    ownerId: string;
    reviews: Array<CampsiteReviewProfile> | null;
    updatedAt: string;
    visits: Array<CampsiteVisitProfile> | null;
};

export type CampsiteReviewProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    campsiteId: string;
    createdAt: string;
    description: string;
    id: string;
    ownerId: string;
    rating: number;
    title: string;
};

export type CampsiteVisitProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    campsiteId: string;
    createdAt: string;
    id: string;
    ownerId: string;
    updatedAt: string;
};

export type CreateCampsiteRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    latitude: number | null;
    longitude: number | null;
    name: string;
};

export type CreateCampsiteReviewRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    rating: number;
    title: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type QueryParameter = {
    Name: string;
    Value: Array<string> | null;
};

export type ToggleCampsiteVisitRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
};

export type UpdateCampsiteRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    latitude?: number;
    longitude?: number;
    name?: string;
};

export type UpdateCampsiteReviewRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    rating?: number;
    title?: string;
};

export type UpdateUserRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UpdateUserRoleRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    role: string;
};

export type UserPrivateProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    role: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type CampsiteProfileWritable = {
    boondockScore: number;
    createdAt: string;
    description: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    ownerId: string;
    reviews: Array<CampsiteReviewProfileWritable> | null;
    updatedAt: string;
    visits: Array<CampsiteVisitProfileWritable> | null;
};

export type CampsiteReviewProfileWritable = {
    campsiteId: string;
    createdAt: string;
    description: string;
    id: string;
    ownerId: string;
    rating: number;
    title: string;
};

export type CampsiteVisitProfileWritable = {
    campsiteId: string;
    createdAt: string;
    id: string;
    ownerId: string;
    updatedAt: string;
};

export type CreateCampsiteRequestWritable = {
    description: string;
    latitude: number | null;
    longitude: number | null;
    name: string;
};

export type CreateCampsiteReviewRequestWritable = {
    description: string;
    rating: number;
    title: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type UpdateCampsiteRequestWritable = {
    description?: string;
    latitude?: number;
    longitude?: number;
    name?: string;
};

export type UpdateCampsiteReviewRequestWritable = {
    description?: string;
    rating?: number;
    title?: string;
};

export type UpdateUserRequestWritable = {
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UpdateUserRoleRequestWritable = {
    role: string;
};

export type UserPrivateProfileWritable = {
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    role: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfileWritable = {
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type PostCampsitesData = {
    body: CreateCampsiteRequestWritable;
    path?: never;
    query?: never;
    url: '/campsites';
};

export type PostCampsitesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesError = PostCampsitesErrors[keyof PostCampsitesErrors];

export type PostCampsitesResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type PostCampsitesResponse = PostCampsitesResponses[keyof PostCampsitesResponses];

export type PostCampsitesSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/campsites/search';
};

export type PostCampsitesSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesSearchError = PostCampsitesSearchErrors[keyof PostCampsitesSearchErrors];

export type PostCampsitesSearchResponses = {
    /**
     * OK
     */
    200: Array<CampsiteProfile> | null;
};

export type PostCampsitesSearchResponse = PostCampsitesSearchResponses[keyof PostCampsitesSearchResponses];

export type PostCampsitesByCampsiteIdReviewsData = {
    body: CreateCampsiteReviewRequestWritable;
    path: {
        campsiteId: string;
    };
    query?: never;
    url: '/campsites/{campsiteId}/reviews';
};

export type PostCampsitesByCampsiteIdReviewsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesByCampsiteIdReviewsError = PostCampsitesByCampsiteIdReviewsErrors[keyof PostCampsitesByCampsiteIdReviewsErrors];

export type PostCampsitesByCampsiteIdReviewsResponses = {
    /**
     * OK
     */
    200: CampsiteReviewProfile;
};

export type PostCampsitesByCampsiteIdReviewsResponse = PostCampsitesByCampsiteIdReviewsResponses[keyof PostCampsitesByCampsiteIdReviewsResponses];

export type PostCampsitesByCampsiteIdVisitsData = {
    body: ToggleCampsiteVisitRequest;
    path: {
        campsiteId: string;
    };
    query?: never;
    url: '/campsites/{campsiteId}/visits';
};

export type PostCampsitesByCampsiteIdVisitsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesByCampsiteIdVisitsError = PostCampsitesByCampsiteIdVisitsErrors[keyof PostCampsitesByCampsiteIdVisitsErrors];

export type PostCampsitesByCampsiteIdVisitsResponses = {
    /**
     * OK
     */
    200: CampsiteVisitProfile;
};

export type PostCampsitesByCampsiteIdVisitsResponse = PostCampsitesByCampsiteIdVisitsResponses[keyof PostCampsitesByCampsiteIdVisitsResponses];

export type DeleteCampsitesByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type DeleteCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteCampsitesByIdError = DeleteCampsitesByIdErrors[keyof DeleteCampsitesByIdErrors];

export type DeleteCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type DeleteCampsitesByIdResponse = DeleteCampsitesByIdResponses[keyof DeleteCampsitesByIdResponses];

export type GetCampsitesByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type GetCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCampsitesByIdError = GetCampsitesByIdErrors[keyof GetCampsitesByIdErrors];

export type GetCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type GetCampsitesByIdResponse = GetCampsitesByIdResponses[keyof GetCampsitesByIdResponses];

export type PatchCampsitesByIdData = {
    body: UpdateCampsiteRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type PatchCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchCampsitesByIdError = PatchCampsitesByIdErrors[keyof PatchCampsitesByIdErrors];

export type PatchCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type PatchCampsitesByIdResponse = PatchCampsitesByIdResponses[keyof PatchCampsitesByIdResponses];

export type GetDatabaseHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/health';
};

export type GetDatabaseHealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDatabaseHealthError = GetDatabaseHealthErrors[keyof GetDatabaseHealthErrors];

export type GetDatabaseHealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDatabaseHealthResponse = GetDatabaseHealthResponses[keyof GetDatabaseHealthResponses];

export type PostDatabaseMigrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/migrations';
};

export type PostDatabaseMigrationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostDatabaseMigrationsError = PostDatabaseMigrationsErrors[keyof PostDatabaseMigrationsErrors];

export type PostDatabaseMigrationsResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostDatabaseMigrationsResponse = PostDatabaseMigrationsResponses[keyof PostDatabaseMigrationsResponses];

export type PostReviewsSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/reviews/search';
};

export type PostReviewsSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostReviewsSearchError = PostReviewsSearchErrors[keyof PostReviewsSearchErrors];

export type PostReviewsSearchResponses = {
    /**
     * OK
     */
    200: Array<CampsiteReviewProfile> | null;
};

export type PostReviewsSearchResponse = PostReviewsSearchResponses[keyof PostReviewsSearchResponses];

export type DeleteReviewsByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type DeleteReviewsByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteReviewsByIdError = DeleteReviewsByIdErrors[keyof DeleteReviewsByIdErrors];

export type DeleteReviewsByIdResponses = {
    /**
     * OK
     */
    200: CampsiteReviewProfile;
};

export type DeleteReviewsByIdResponse = DeleteReviewsByIdResponses[keyof DeleteReviewsByIdResponses];

export type GetReviewsByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type GetReviewsByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetReviewsByIdError = GetReviewsByIdErrors[keyof GetReviewsByIdErrors];

export type GetReviewsByIdResponses = {
    /**
     * OK
     */
    200: CampsiteReviewProfile;
};

export type GetReviewsByIdResponse = GetReviewsByIdResponses[keyof GetReviewsByIdResponses];

export type PatchReviewsByIdData = {
    body: UpdateCampsiteReviewRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type PatchReviewsByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchReviewsByIdError = PatchReviewsByIdErrors[keyof PatchReviewsByIdErrors];

export type PatchReviewsByIdResponses = {
    /**
     * OK
     */
    200: CampsiteReviewProfile;
};

export type PatchReviewsByIdResponse = PatchReviewsByIdResponses[keyof PatchReviewsByIdResponses];

export type DeleteUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteUsersMeError = DeleteUsersMeErrors[keyof DeleteUsersMeErrors];

export type DeleteUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type DeleteUsersMeResponse = DeleteUsersMeResponses[keyof DeleteUsersMeResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: UpdateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type PostUsersSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/users/search';
};

export type PostUsersSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUsersSearchError = PostUsersSearchErrors[keyof PostUsersSearchErrors];

export type PostUsersSearchResponses = {
    /**
     * OK
     */
    200: Array<UserPublicProfile> | null;
};

export type PostUsersSearchResponse = PostUsersSearchResponses[keyof PostUsersSearchResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * OK
     */
    200: UserPublicProfile;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PatchUsersByIdRoleData = {
    body: UpdateUserRoleRequestWritable;
    path: {
        /**
         * ID (UUID) of the user whose role is being changed
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/role';
};

export type PatchUsersByIdRoleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchUsersByIdRoleError = PatchUsersByIdRoleErrors[keyof PatchUsersByIdRoleErrors];

export type PatchUsersByIdRoleResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PatchUsersByIdRoleResponse = PatchUsersByIdRoleResponses[keyof PatchUsersByIdRoleResponses];

export type PostVisitsSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/visits/search';
};

export type PostVisitsSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostVisitsSearchError = PostVisitsSearchErrors[keyof PostVisitsSearchErrors];

export type PostVisitsSearchResponses = {
    /**
     * OK
     */
    200: Array<CampsiteVisitProfile> | null;
};

export type PostVisitsSearchResponse = PostVisitsSearchResponses[keyof PostVisitsSearchResponses];
