// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CampsiteProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdAt: string;
    description: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    ownerId: string;
    updatedAt: string;
};

export type CreateCampsiteRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Description: string;
    Latitude: number | null;
    Longitude: number | null;
    Name: string;
};

export type CreateUserRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    AuthId: string;
    Email: string;
    Username: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type QueryParameter = {
    Name: string;
    Value: Array<string> | null;
};

export type UpdateCampsiteRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    latitude?: number;
    longitude?: number;
    name?: string;
};

export type UpdateUserRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UserPrivateProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type CampsiteProfileWritable = {
    createdAt: string;
    description: string;
    id: string;
    latitude: number;
    longitude: number;
    name: string;
    ownerId: string;
    updatedAt: string;
};

export type CreateCampsiteRequestWritable = {
    Description: string;
    Latitude: number | null;
    Longitude: number | null;
    Name: string;
};

export type CreateUserRequestWritable = {
    AuthId: string;
    Email: string;
    Username: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type UpdateCampsiteRequestWritable = {
    description?: string;
    latitude?: number;
    longitude?: number;
    name?: string;
};

export type UpdateUserRequestWritable = {
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UserPrivateProfileWritable = {
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfileWritable = {
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type PostCampsitesData = {
    body: CreateCampsiteRequestWritable;
    path?: never;
    query?: never;
    url: '/campsites';
};

export type PostCampsitesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesError = PostCampsitesErrors[keyof PostCampsitesErrors];

export type PostCampsitesResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type PostCampsitesResponse = PostCampsitesResponses[keyof PostCampsitesResponses];

export type PostCampsitesSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/campsites/search';
};

export type PostCampsitesSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostCampsitesSearchError = PostCampsitesSearchErrors[keyof PostCampsitesSearchErrors];

export type PostCampsitesSearchResponses = {
    /**
     * OK
     */
    200: Array<CampsiteProfile> | null;
};

export type PostCampsitesSearchResponse = PostCampsitesSearchResponses[keyof PostCampsitesSearchResponses];

export type DeleteCampsitesByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type DeleteCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteCampsitesByIdError = DeleteCampsitesByIdErrors[keyof DeleteCampsitesByIdErrors];

export type DeleteCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type DeleteCampsitesByIdResponse = DeleteCampsitesByIdResponses[keyof DeleteCampsitesByIdResponses];

export type GetCampsitesByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type GetCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCampsitesByIdError = GetCampsitesByIdErrors[keyof GetCampsitesByIdErrors];

export type GetCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type GetCampsitesByIdResponse = GetCampsitesByIdResponses[keyof GetCampsitesByIdResponses];

export type PatchCampsitesByIdData = {
    body: UpdateCampsiteRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/campsites/{id}';
};

export type PatchCampsitesByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchCampsitesByIdError = PatchCampsitesByIdErrors[keyof PatchCampsitesByIdErrors];

export type PatchCampsitesByIdResponses = {
    /**
     * OK
     */
    200: CampsiteProfile;
};

export type PatchCampsitesByIdResponse = PatchCampsitesByIdResponses[keyof PatchCampsitesByIdResponses];

export type GetDatabaseHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/health';
};

export type GetDatabaseHealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDatabaseHealthError = GetDatabaseHealthErrors[keyof GetDatabaseHealthErrors];

export type GetDatabaseHealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDatabaseHealthResponse = GetDatabaseHealthResponses[keyof GetDatabaseHealthResponses];

export type PostDatabaseMigrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/migrations';
};

export type PostDatabaseMigrationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostDatabaseMigrationsError = PostDatabaseMigrationsErrors[keyof PostDatabaseMigrationsErrors];

export type PostDatabaseMigrationsResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostDatabaseMigrationsResponse = PostDatabaseMigrationsResponses[keyof PostDatabaseMigrationsResponses];

export type PostUsersData = {
    body: CreateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteUsersMeError = DeleteUsersMeErrors[keyof DeleteUsersMeErrors];

export type DeleteUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type DeleteUsersMeResponse = DeleteUsersMeResponses[keyof DeleteUsersMeResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: UpdateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type PostUsersSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/users/search';
};

export type PostUsersSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUsersSearchError = PostUsersSearchErrors[keyof PostUsersSearchErrors];

export type PostUsersSearchResponses = {
    /**
     * OK
     */
    200: Array<UserPublicProfile> | null;
};

export type PostUsersSearchResponse = PostUsersSearchResponses[keyof PostUsersSearchResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * OK
     */
    200: UserPublicProfile;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];
